<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:700,900" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="css/normalize.css"/>
    <!--Animate on Scroll-->
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">git
    <!--Favicon-->
    <link rel="apple-touch-icon" sizes="180x180" href="img/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/favicon/favicon-16x16.png">
    <link rel="manifest" href="img/favicon/site.webmanifest">
    <link rel="stylesheet" type="text/css" href="css/style.css"/>
    <title>Portfolio de Jean Liautaud</title>
</head>

<body class="container center" id="home">
<header class="darkBackground">
    <nav data-aos="fade-right" class="menu">
        <ul class="hidden">
            <li><a href="#home">Accueil</a></li>
            <li><a href="#projets">Projets</a></li>
            <li><a href="#sites">Sites</a></li>
            <li><a href="#langages">Langages</a></li>
            <li><a href="#tools">Outils</a></li>
            <li><a href="#contact">Contact</a></li>
        </ul>
        <ul>
            <li><a class="js-scrollTo" href="#home" title="Accueil"><i class="fas fa-home"></i></a></li>
            <li><a class="js-scrollTo" href="#projets" title="Projets personnels"><i class="fas fa-user"></i></a></li>
            <li><a class="js-scrollTo" href="#sites" title="Sites"><i class="fas fa-sitemap"></i></a></li>
            <li><a class="js-scrollTo" href="#langages" title="Langages"><i class="fas fa-code"></i></a></li>
            <li><a class="js-scrollTo" href="#tools" title="Outils"><i class="fas fa-tools"></i></a></li>
            <li><a class="js-scrollTo" href="#contact" title="Contact"><i class="fas fa-envelope"></i></a></li>
        </ul>
    </nav>
    <h1 data-aos="zoom-in" data-aos-duration="2000">Jean Liautaud</h1>
    <h2>Développeur</h2>
    <h2>Intégrateur Web</h2>
    <h2>Junior</h2>
</header>
<main>
    <section id="projets" class="orangeBackground aos-item">
        <h3>Projets personnels</h3>
        <figure>
            <figcaption>Omnicuiseur (recettes)
                <div>
                    <img src="img/html5.jpg" alt="HTML5" class="thumbnail">
                    <img src="img/css3.png" alt="CSS4" class="thumbnail">
                    <img src="img/js.png" alt="JS" class="thumbnail">
                    <img src="img/jquery.gif" alt="jQuery" class="thumbnail">
                    <img src="img/php.png" alt="PHP" class="thumbnail">
                    <img src="img/mySQL.png" alt="MySQL" class="thumbnail">
                </div>
            </figcaption>
            <a href="https://omnicuiseur.jeanliautaud.fr"
               title="Gestion de recettes pour l'Omnicuiseur Vitalité. Responsive">
                <img src="img/omnicuiseur.jpg" alt="Omnicuiseur">
            </a>
        </figure>

        <figure>
            <figcaption>Simon
                <div>
                    <img src="img/html5.jpg" alt="HTML5" class="thumbnail">
                    <img src="img/css3.png" alt="CSS4" class="thumbnail">
                    <img src="img/js.png" alt="JS" class="thumbnail">
                </div>
            </figcaption>
            <a href="https://simon.jeanliautaud.fr" title="Le jeu Simon, en JS">
                <img src="img/simon.png" alt="Simon">
            </a>
        </figure>
        
        <figure>
            <figcaption>Memory &ndash; GIFs Animées (React)
                <div>
                    <img src="img/html5.jpg" alt="HTML5" class="thumbnail">
                    <img src="img/css3.png" alt="CSS4" class="thumbnail">
                    <img src="img/react.gif" alt="React" class="thumbnail">
                </div>
            </figcaption>
            <a href="https://memory.jeanliautaud.fr" title="Memory en React">
                <img src="img/memory.png" alt="Memory">
            </a>
        </figure>
        <figure>
            <figcaption>Sudoku (React)
                <div>
                    <img src="img/html5.jpg" alt="HTML5" class="thumbnail">
                    <img src="img/css3.png" alt="CSS4" class="thumbnail">
                    <img src="img/react.gif" alt="React" class="thumbnail">
                </div>
            </figcaption>
            <a href="https://sudoku.jeanliautaud.fr" title="Sudoku en React">
                <img src="img/sudoku.png" alt="Sudoku">
            </a>
        </figure>
        <figure>
            <figcaption>Surface de Boy
                <img src="img/html5.jpg" alt="HTML5" class="thumbnail">
                <img src="img/css3.png" alt="CSS4" class="thumbnail">
                <img src="img/js.png" alt="JS" class="thumbnail">
            </figcaption>
            <a href="//surfacedeboy.jeanliautaud.fr/index.html"
               title="Dessin d'un objet topologique, avec paramètres modifiables.">
                <img src="img/surfaceBoy-small.jpg" alt="Surface de Boy">
            </a>
        </figure>
        <figure>
            <figcaption>Pixellisation
                <img src="img/html5.jpg" alt="HTML5" class="thumbnail">
                <img src="img/css3.png" alt="CSS4" class="thumbnail">
                <img src="img/js.png" alt="JS" class="thumbnail">
                <img src="img/jquery.gif" alt="jQuery" class="thumbnail">
            </figcaption>
            <a href="//pixellisation.jeanliautaud.fr/index.html" title="Pixellisation variable d'une image. En JS POO">
                <img src="img/pixellisation-small.jpg" alt="Pixellisation">
            </a>
        </figure>
    </section>

    <section id="sites" class="sites darkBackground aos-item">
        <h3>Sites</h3>
        <h4>Quelques exercices réalisés dans le cadre de ma formation à la 3W&nbsp;Academy</h4>
        <figure>
            <figcaption>Mind Geek
                <img src="img/html5.jpg" alt="HTML5" class="thumbnail">
                <img src="img/css3.png" alt="CSS4" class="thumbnail">
            </figcaption>
            <a href="//mindgeek.jeanliautaud.fr" title="Intégration d'un site d'hébergement. Responsive">
                <img src="img/mind_geek_small.jpg" alt="Mind Geek">
            </a>
        </figure>
        <figure>
            <figcaption>Cup of Tea
                <img src="img/html5.jpg" alt="HTML5" class="thumbnail">
                <img src="img/css3.png" alt="CSS4" class="thumbnail">
            </figcaption>
            <a href="//cupoftea.jeanliautaud.fr" title="Intégration d'un site de vente de thé. Responsive">
                <img src="img/cup_of_tea_small.jpg" alt="Cup of Tea">
            </a>
        </figure>
    </section>

    <section id="langages" class="langages orangeBackground aos-item">
        <h3>Langages</h3>
        <figure><img src="img/html5.jpg" alt="Html5"></figure>
        <figure><img src="img/css3.png" alt="Css3"></figure>
        <figure><img src="img/js.png" alt="JS"></figure>
        <figure><img src="img/jquery.gif" alt="Jquery"></figure>
        <figure><img src="img/php.png" alt="Php"></figure>
        <figure><img src="img/mySQL.png" alt="MySQL"></figure>
    </section>
    <section id="tools" class="tools darkBackground aos-item">
        <h3>Outils</h3>
        <figure><img src="img/sass.png" alt="Sass"></figure>
        <figure><img src="img/git.png" alt="Git"></figure>
        <figure><img src="img/Phpstorm.png" alt="Phpstorm"></figure>
    </section>

    <section id="contact" class="orangeBackground">
        <h3>Contact</h3>
        <script src="js/mail.js"></script>
        <script> protectMyEmail() </script>
        <p><a href="https://github.com/JeanLi06">Github</a></p>
        <p><a href="https://www.linkedin.com/in/jean-liautaud-72a194174/">LinkedIn</a></p>
        <p><a href="" id="myBtn" title="Image de mon C.V.">C.V.</a></p>
        <p><a href="files/cv.pdf" title="Fichier Acrobat de mon C.V."><i class="far fa-file-pdf"></i></a></p>
        <!-- The CV Modal -->
        <div id="myModal" class="modal">
            <!-- CV Modal contenu -->
            <div class="modal-content">
                <span class="close">X</span>
                <img src="img/cv.png" alt="CV">
            </div>

        </div>
    </section>
</main>
<script src="js/script.js"></script>
<script src="js/cv-modal.js"></script>
<!-- Librairie Animate On Scroll -->
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script> AOS.init({
    startEvent: 'DOMContentLoaded',
    once: true,// l'animation ne doit se produire qu'une seule fois.
    disableMutationObserver: false,
    anchorPlacement: 'top-bottom',
    // offset: -175
  })
</script>
</body>
</html>